# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02fe544890ce065c3636e8a490daf82fd3734375331f5b577e0e8b58dbdd57ca84e4d66bc508321352dbb3a398a6b36ce631911db428ee764fdebd3bac7569e0

test:
  secret_key_base: f46e98a8030f196264fc24ca3cce86097b9680026c71573e3f6e8d797f93194617d7e2e747a2e8c1303b0e5d381055a644b7ef59f18149658c393780dd39fd6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
